/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mitumc.sample;

import org.mitumc.sdk.key.Keypair;

public class App {
    public static void main(String[] args) {
        Keypair kp = Keypair.create();
        Keypair pkp = Keypair.fromPrivateKey("KyyxjcJQuZ9VjcooDg5QMPBn1KmWQTqyKYhxv8mvEZZYmuTu55HBmpr");
        Keypair skp = Keypair.fromSeed("seedseedseedseedseedseedseedseedseedseedseedseedseedseedseed");

        System.out.println("----------------------------------------------------------- New Keypair");
        System.out.println(kp.getPrivateKey());
        System.out.println(kp.getPublicKey());

        System.out.println("----------------------------------------------------------- from Private Key");
        System.out.println(pkp.getPrivateKey());
        System.out.println(pkp.getPublicKey());

        System.out.println("----------------------------------------------------------- from Seed");
        System.out.println(skp.getPrivateKey());
        System.out.println(skp.getPublicKey());
    }
}
